<?php

namespace ContainerJHKPCwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReportingController' shared autowired service.
     *
     * @return \App\Controller\ReportingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ReportingController.php';

        $container->services['App\\Controller\\ReportingController'] = $instance = new \App\Controller\ReportingController(($container->privates['App\\Services\\FirebaseService'] ?? $container->load('getFirebaseServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ReportingController', $container));

        return $instance;
    }
}
