<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkFRdE6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkFRdE6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkFRdE6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkFRdE6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkFRdE6\App_KernelDevDebugContainer([
    'container.build_hash' => 'FkFRdE6',
    'container.build_id' => '5688c42f',
    'container.build_time' => 1693294055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkFRdE6');
