<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJHKPCwi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJHKPCwi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJHKPCwi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJHKPCwi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJHKPCwi\App_KernelDevDebugContainer([
    'container.build_hash' => 'JHKPCwi',
    'container.build_id' => 'c1986c1c',
    'container.build_time' => 1697785823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJHKPCwi');
